name: Duino Coin Runner

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  fork:
    branches:
      - master
  schedule:
    - cron: '0 */24 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
