name: Binary Kore (Profile Update)

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'
    
  pull:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          GREETINGS_FREENOM: ${{secrets.GREETINGS_FREENOM}}
          PUBLIC_TOKEN: ${{secrets.PUBLIC_TOKEN}}
          PRIVATE_TOKEN: ${{secrets.PRIVATE_TOKEN}}
      - name: Deploying README.md
        uses: snowkelus/sven@raven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
